name: bloc_event
description: Make the Bloc Events easier to structure
version: 1.0.0
author: Martin FÃ¶rster - Brickmakers <martin.foerster@brickmakers.de>
homepage: https://github.com/Ownii/dart_bloc_event

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^0.15.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
